---
title: "Neurolucida Sheet Sorter"
author: "haley.speed@yahoo.com"
date: "2018/01/18"
output: html_notebook
---

<h2> Variables for the user to change </h2>

```{r}


# Directory to the files to be analyzed (in the format: "C:\\Users\\hspeed")
inFile.dir <- "C:\\Users\\hspeed\\Dropbox\\Sync Data Analysis Computers\\Gulf War Project\\Statistics\\R Scripts\\Morphology\\Apical\\NL360 Excel Files\\oil_saline"

# Treatment group (use # sign to comment out all but the current group)
inFile.group <- "wt_vehicle"

# Default values
microns <- 10              # Spine density calculated per 10 microns
sholl.distance1 <- 150     # Sholl ring 1 from 0-150
sholl.distance2 <- 300     # Sholl ring 2 from 150-300
sholl.distance3 <- 500     # Sholl ring 3 from 300-500



```

<b> Import Packages <b>

```{r}

library(openxlsx)
library(dplyr)
```


```{r}


# Function to calculate spine density by branch order
getBranching <- function (sheet){
        
        spines <- c()
        thin <- c()
        stubby <- c()
        shroom <- c()
        podia <- c()
        
        for (i in sheet$Order){
                spines[i] <- as.numeric(as.character(sheet[i,17]))/
                             as.numeric(as.character(sheet[i,3])) * microns
                thin[i]   <- as.numeric(as.character(sheet[i,19]))/
                             as.numeric(as.character(sheet[i,3])) * microns
                stubby[i] <- as.numeric(as.character(sheet[i,20]))/
                             as.numeric(as.character(sheet[i,3])) * microns
                shroom[i] <- as.numeric(as.character(sheet[i,21]))/
                             as.numeric(as.character(sheet[i,3])) * microns
                podia[i]  <- as.numeric(as.character(sheet[i,22]))/
                             as.numeric(as.character(sheet[i,3])) * microns
        }
        
        return(as.data.frame(cbind(order = sheet[,1], length = sheet[,3], 
                     surfaceArea = sheet[,6], volume = sheet[,9],
                     spines = spines, thin = thin, stubby = stubby, 
                     mushroom = shroom, filopodia = podia)))
}
        
# Function to caulculate spine density by distance from soma
getDistance <- function (sheet) {
        
        # Number indicates start distance of Sholl ring
        sholl.spines1 <- 0    # Number of spines from 0 to sholl ring 1
        sholl.spines2 <- 0    # Number of spines from sholl ring 1 to sholl ring 2
        sholl.spines3 <- 0    # Number of spines from sholl ring 2 to sholl ring 3
        sholl.spines4 <- 0    # Number of spines after sholl ring 4
        
        sholl.length1 <- 0    # length of dendrites from 0 to sholl ring 1
        sholl.length2 <- 0    # length of dendrites from sholl ring 1 to sholl ring 2
        sholl.length3 <- 0    # length of dendrites from sholl ring 2 to sholl ring 3
        sholl.length4 <- 0    # length of dendrites after sholl ring 4
        
        sholl.label1 <- paste("0", sholl.distance1, sep = "-")
        sholl.label2 <- paste(sholl.distance1, sholl.distance2, sep = "-")
        sholl.label3 <- paste(sholl.distance2, sholl.distance3, sep = "-")
        sholl.label4 <- paste(sholl.distance3, "+")
        
        row = 0
        
        # Caculate sums of spine number and length for each Sholl ring
        for (i in sheet[,1]) {
                
                i <- as.numeric(as.character(i))
                row <- (i+10)/10
                spines <- as.numeric(as.character(sheet[row,4]))
                length <- as.numeric(as.character(sheet[row,6]))
                
                if (i < sholl.distance1 & is.na(spines) == FALSE) {
                        sholl.spines1 <- sholl.spines1 + spines
                        sholl.length1 <- sholl.length1 + length
                        
                } else if (i >= sholl.distance1 & i < sholl.distance2 & is.na(spines) == FALSE) {
                        sholl.spines2 <- sholl.spines2 + spines
                        sholl.length2 <- sholl.length2 + length
                        
                } else if (i >= sholl.distance2 & i < sholl.distance3 & is.na(spines) == FALSE) {
                        sholl.spines3 <- sholl.spines3 + spines
                        sholl.length3 <- sholl.length3 + length
                } else if (i >= sholl.distance3 & is.na(spines) == FALSE) {
                        sholl.spines4 <- sholl.spines4 + spines
                        sholl.length4 <- sholl.length4 + length
                }
        }
                
        # Calculate the density of spines for each Sholl ring 
        sholl.density1    <- sholl.spines1 / sholl.length1 * microns
        sholl.density2    <- sholl.spines2 / sholl.length2 * microns
        sholl.density3    <- sholl.spines3 / sholl.length3 * microns
        sholl.density4    <- sholl.spines4 / sholl.length4 * microns

        distance       <- c(sholl.label1, sholl.label2, sholl.label3, sholl.label4)
        spineNumber    <- c(sholl.spines1, sholl.spines2, sholl.spines3, sholl.spines4)
        dendriteLength <- c(sholl.length1, sholl.length2, sholl.length3, sholl.length4)
        spineDensity   <- c(sholl.density1, sholl.density2, sholl.density3, sholl.density4)

        return(as.data.frame(cbind(distance = distance, spineNumber, 
                                   dendriteLength, spineDensity)))
}

# Function to calculate Spine density for the whole dendrite
# Spine density could have been taken from the Tree Spines-Dendrite sheet, 
# but to save on memory, it was more efficient to just calculate it here.
# Note that these are spines/10 microns, not spines/1 micron as in the 
# Tree Spines-Dendrite Worksheet.
getTotal <- function (sheet.neuron, sheet.spines, sheet.branching){
        
        # Dendrite Length
        dendrite.length <- as.numeric(as.character(sheet.neuron[3,14]))
        
        # Dendrite Surface Area
        dendrite.surface <- as.numeric(as.character(sheet.neuron[3,18]))
        
        # Dendrite Volume
        dendrite.volume <- as.numeric(as.character(sheet.neuron[3,20]))
        
        # Dendrite branches
        dendrite.branches <-as.numeric(as.character(sheet.branching[,2]))
        dendrite.branches <- sum(dendrite.branches[!is.na(dendrite.branches)])
        
        # Dendrite branch orders
        dendrite.order <- length(sheet.branching[,1])
        

        # Spine Area
        spine.area <- as.numeric(as.character(sheet.spines[,9]))
        spine.area <- mean(spine.area[!is.na(spine.area)])
        
        # Spine Volume
        spine.volume <- as.numeric(as.character(sheet.spines[,7]))
        spine.volume <- mean(spine.volume[!is.na(spine.volume)])
        
        # Spine Density
        spines <- as.numeric(as.character(sheet.neuron[3,5])) / dendrite.length * microns
        thin   <- as.numeric(as.character(sheet.neuron[3,7])) / dendrite.length * microns
        stubby <- as.numeric(as.character(sheet.neuron[3,8])) / dendrite.length * microns
        shroom <- as.numeric(as.character(sheet.neuron[3,9])) / dendrite.length * microns
        podia  <- as.numeric(as.character(sheet.neuron[3,10])) / dendrite.length * microns

        
        return (c(dendrite.length, dendrite.surface,dendrite.volume, 
                      dendrite.branches,dendrite.order, spine.area, 
                      spine.volume, spines, thin, stubby, shroom, podia))
}

# Function to write collated data to file
write.outFile <- function (outFile.data, outFile.fileName, outFile.base){
        # Check to see if the summary ouput file currently exists
        # If so, read it into a dataframe
        # Check to see if the current cell has already been entered
        # If so, overwrite the data for that cell
        # Write to the summary file
        if (file.exists(outFile.fileName)) {
                outFile.existing <- read.csv(outFile.fileName, 
                                             header=TRUE, sep =",", 
                                             stringsAsFactors = FALSE)
                outFile.keep <- filter(outFile.existing, 
                                       outFile.existing$cell != outFile.base)
                outFile.keep <- rbind(outFile.keep,outFile.data)
                write.csv(outFile.keep, outFile.fileName, row.names = FALSE)
        } else { write.csv(outFile.data, outFile.fileName, row.names = FALSE) }
        
}

```


## Run the script

```{r}
# Get directory contents 
inFile.name<- dir(inFile.dir, pattern = "*.xlsx")
setwd(inFile.dir)

# Set output directory
outFile.dir <- paste(inFile.dir, "analyzed", sep = '//')
if (!dir.exists(outFile.dir)){
        dir.create(file.path(outFile.dir))
}

# Get contents from each file
for (i in 1:length(inFile.name)){
      
     # Open the file and read the relevant sheets:
     # 3 - Tree Totals-Dendrite, 5 - Neuron Summary,
     # 12 - Tortuous Distance - Dendrite, 6 - Spine Details
     sheet.branching <- read.xlsx(inFile.name[i], sheet =  3, colNames=TRUE)
     sheet.neuron    <- read.xlsx(inFile.name[i], sheet = 5, colNames=TRUE)
     sheet.distance  <- read.xlsx(inFile.name[i], sheet = 12, colNames = TRUE)
     sheet.spines    <- read.xlsx(inFile.name[i], sheet = 6, colNames = TRUE)

     # Summary data by branch order, distance from soma, and the entire 
     # apical dendrite
     branching   <- getBranching(sheet.branching)   
     distance    <- getDistance(sheet.distance)         
     total <- getTotal(sheet.neuron, sheet.spines, sheet.branching)


     # Write data to file

     # Construct the pathname based on the original file name
     outFile.base         <- strsplit(inFile.name[i], ".xlsx")
     outFile.branching    <- paste(outFile.base[1],"-by branch order.csv", sep = "")
     outFile.branching    <- paste(outFile.dir,outFile.branching, sep = "\\")
     outFile.distance     <- paste(outFile.base[1],"-by distance.csv", sep = "")
     outFile.distance     <- paste(outFile.dir,outFile.distance, sep = "\\")
     outFile.allBranching <- paste(inFile.group, "_branching.csv", sep = "")
     outFile.allBranching <- paste(outFile.dir,outFile.allBranching, sep = "\\")
     outFile.allDistance  <- paste(inFile.group, "_distance.csv", sep = "")
     outFile.allDistance  <- paste(outFile.dir,outFile.allDistance, sep = "\\")
     outFile.summary      <- paste(inFile.group, "_summary.csv", sep = "")
     outFile.summary      <- paste(outFile.dir,outFile.summary, sep = "\\")

     write.csv(branching,outFile.branching, row.names = FALSE)
     write.csv(distance,outFile.distance, row.names = FALSE)

     # Assemble data to be written to the summary table
     outFile.summaryData <- as.data.frame(c(outFile.base[1], total))
     colnames(outFile.summaryData) <- c("cell","dendriteLength", "dendriteSurfaceArea", 
                                "dendriteVolume", "dendriteBranches", 
                                "dendriteOrders", "spineArea", "spineVolume", 
                                "totalSpines", "thinSpines", "stubbySpines", 
                                "mushroomSpines", "filopodia")
     write.outFile(outFile.summaryData, outFile.summary, outFile.base)

     # Assemble data to be written to the allBranches table
     outFile.branchData <- cbind(outFile.base, branching)
     colnames(outFile.branchData) <- c("cell", "order", "dendriteLength", 
                                  "dendriteSurfaceArea", "dendriteVolume", 
                                  "spines", "thin", "stubby", 
                                  "mushroom", "filopodia")
     write.outFile(outFile.branchData, outFile.allBranching, outFile.base)

     # Assemble data to be written to the allDistance table
     outFile.distanceData <- cbind(outFile.base, distance)
     colnames(outFile.distanceData) <- c("cell", "distance", "dendriteLength", 
                                  "spineNumber", "spineDensity")
     write.outFile(outFile.distanceData, outFile.allDistance, outFile.base)
}
```

